### ISSUE TITLE
Where to download product image features?

### ISSUE THREAD

**Issue by xicaixiaomogu** [nhtsai/graph-rec#2]
how can I get this file :/teams/DSC180A_FA20_A00/b01graphdataanalysis/personal-nhtsai/image_features_Electronics.b

**Comment by nhtsai** [comment]
Hi @xicaixiaomogu,

The image features are from the old 2014 Amazon dataset. The dataset has since been updated, but it seems like the image features are still available on the 2014 dataset website (see https://snap.stanford.edu/data/amazon/productGraph/image_features/categoryFiles/).

However, I recommend using the updated 2023 dataset and generating feature vectors yourself using the provided image URLs.

According to the researchers, the feature vectors were generated by passing the images through a pre-trained ImageNet model. 

> We extracted visual features from each product image using a deep CNN (see citation below). Image features are stored in a binary format, which consists of 10 characters (the product ID), followed by 4096 floats (repeated for every product).

Please see the following papers for more information regarding the image feature extraction process.

> Ups and downs: Modeling the visual evolution of fashion trends with one-class collaborative filtering
> Ruining He, Julian McAuley
> WWW, 2016
> [pdf](https://cseweb.ucsd.edu/~jmcauley/pdfs/www16a.pdf)
> 
> Image-based recommendations on styles and substitutes
> Julian McAuley, Christopher Targett, Javen Shi, Anton van den Hengel
> SIGIR, 2015
> [pdf](https://cseweb.ucsd.edu/~jmcauley/pdfs/sigir15.pdf)

Hope this helps!
